     1|# Copyright 2020 The Chromium Authors
     2|# Use of this source code is governed by a BSD-style license that can be
     3|# found in the LICENSE file.
     4|
     5|# To regenerate this list, run:
     6|# sed -i '/^[^#][^[]*$/d' chrome_java_resources.gni
     7|# (for f in $(find java/res/*/ -type f); do echo '  "'$f'",'; done; echo ']') >> chrome_java_resources.gni
     8|# git cl format
     9|
    10|chrome_java_resources = [
    11|  "java/res/anim/accelerate_quart.xml",
    12|  "java/res/anim/activity_close_exit.xml",
    13|  "java/res/anim/activity_open_enter.xml",
    14|  "java/res/anim/decelerate_quart.xml",
    15|  "java/res/anim/fast_fade_out.xml",
    16|  "java/res/anim/fast_out_slow_in_interpolator.xml",
    17|  "java/res/anim/slide_in_down.xml",
    18|  "java/res/anim/slide_in_left.xml",
    19|  "java/res/anim/slide_in_right.xml",
    20|  "java/res/anim/slide_in_up.xml",
    21|  "java/res/anim/slide_out_down.xml",
    22|  "java/res/anim/slide_out_left.xml",
    23|  "java/res/anim/view_flipper_fade_in.xml",
    24|  "java/res/anim/view_flipper_fade_out.xml",
    25|  "java/res/color-night/distilled_page_pref_background_color.xml",
    26|  "java/res/color-night/widget_bg.xml",
    27|  "java/res/color-night/widget_button_bg.xml",
    28|  "java/res/color-night/widget_searchbox_bg.xml",
    29|  "java/res/color-night/xr_toolbar_bg.xml",
    30|  "java/res/color/distilled_page_pref_background_color.xml",
    31|  "java/res/color/reader_mode_prefs_font_style_button_background_color.xml",
    32|  "java/res/color/reader_mode_prefs_font_style_button_text_color.xml",
    33|  "java/res/color/reader_mode_prefs_theme_button_stroke_color.xml",
    34|  "java/res/color/tile_bg_color_list.xml",
    35|  "java/res/color/widget_bg.xml",
    36|  "java/res/color/widget_button_bg.xml",
    37|  "java/res/color/widget_searchbox_bg.xml",
    38|  "java/res/color/xr_toolbar_bg.xml",
    39|  "java/res/drawable-hdpi/btn_close_white.png",
    40|  "java/res/drawable-hdpi/btn_tab_close_normal.png",
    41|  "java/res/drawable-hdpi/cvc_icon.png",
    42|  "java/res/drawable-hdpi/cvc_icon_amex.png",
    43|  "java/res/drawable-hdpi/ic_devices_16dp.png",
    44|  "java/res/drawable-hdpi/ic_dialer_icon_blue_40dp.png",
    45|  "java/res/drawable-hdpi/ic_dialer_not_found_red_40dp.png",
    46|  "java/res/drawable-hdpi/ic_download_pause.png",
    47|  "java/res/drawable-hdpi/ic_download_pending.png",
    48|  "java/res/drawable-hdpi/ic_email_googblue_36dp.png",
    49|  "java/res/drawable-hdpi/ic_error_grey800_24dp_filled.png",
    50|  "java/res/drawable-hdpi/ic_error_outline_red_24dp.png",
    51|  "java/res/drawable-hdpi/ic_error_white_24dp_filled.png",
    52|  "java/res/drawable-hdpi/ic_event_googblue_36dp.png",
    53|  "java/res/drawable-hdpi/ic_exit_to_app_white_24dp.png",
    54|  "java/res/drawable-hdpi/ic_file_download_white_24dp.png",
    55|  "java/res/drawable-hdpi/ic_link_grey600_36dp.png",
    56|  "java/res/drawable-hdpi/ic_phone_googblue_36dp.png",
    57|  "java/res/drawable-hdpi/ic_photo_camera.png",
    58|  "java/res/drawable-hdpi/ic_place_googblue_36dp.png",
    59|  "java/res/drawable-hdpi/ic_spark_4c_16dp.png",
    60|  "java/res/drawable-hdpi/incognito_splash.png",
    61|  "java/res/drawable-hdpi/infobar_chrome.png",
    62|  "java/res/drawable-hdpi/infobar_translate.png",
    63|  "java/res/drawable-hdpi/location_bar_incognito_badge.png",
    64|  "java/res/drawable-hdpi/menu_update.png",
    65|  "java/res/drawable-hdpi/offline_pin.png",
    66|  "java/res/drawable-hdpi/open_in_new_tab.png",
    67|  "java/res/drawable-hdpi/permission_push_notification_off.png",
    68|  "java/res/drawable-hdpi/preview_pin_round.png",
    69|  "java/res/drawable-hdpi/progress_bar_background.9.png",
    70|  "java/res/drawable-hdpi/progress_bar_foreground.9.png",
    71|  "java/res/drawable-hdpi/reader_mode_prefs_icon.png",
    72|  "java/res/drawable-hdpi/safetytip_shield.png",
    73|  "java/res/drawable-hdpi/shortcut_incognito.png",
    74|  "java/res/drawable-hdpi/shortcut_newtab.png",
    75|  "java/res/drawable-hdpi/shortcut_newwindow.png",
    76|  "java/res/drawable-hdpi/spinner.png",
    77|  "java/res/drawable-hdpi/spinner_white.png",
    78|  "java/res/drawable-hdpi/tab_group_outline.9.png",
    79|  "java/res/drawable-hdpi/tab_indicator_spinner.png",
    80|  "java/res/drawable-ldrtl/google_pay_with_divider.xml",
    81|  "java/res/drawable-mdpi/btn_close_white.png",
    82|  "java/res/drawable-mdpi/btn_tab_close_normal.png",
    83|  "java/res/drawable-mdpi/cvc_icon.png",
    84|  "java/res/drawable-mdpi/cvc_icon_amex.png",
    85|  "java/res/drawable-mdpi/ic_devices_16dp.png",
    86|  "java/res/drawable-mdpi/ic_dialer_icon_blue_40dp.png",
    87|  "java/res/drawable-mdpi/ic_dialer_not_found_red_40dp.png",
    88|  "java/res/drawable-mdpi/ic_download_pause.png",
    89|  "java/res/drawable-mdpi/ic_download_pending.png",
    90|  "java/res/drawable-mdpi/ic_email_googblue_36dp.png",
    91|  "java/res/drawable-mdpi/ic_error_grey800_24dp_filled.png",
    92|  "java/res/drawable-mdpi/ic_error_outline_red_24dp.png",
    93|  "java/res/drawable-mdpi/ic_error_white_24dp_filled.png",
    94|  "java/res/drawable-mdpi/ic_event_googblue_36dp.png",
    95|  "java/res/drawable-mdpi/ic_exit_to_app_white_24dp.png",
    96|  "java/res/drawable-mdpi/ic_file_download_white_24dp.png",
    97|  "java/res/drawable-mdpi/ic_link_grey600_36dp.png",
    98|  "java/res/drawable-mdpi/ic_phone_googblue_36dp.png",
    99|  "java/res/drawable-mdpi/ic_photo_camera.png",
   100|  "java/res/drawable-mdpi/ic_place_googblue_36dp.png",
   101|  "java/res/drawable-mdpi/ic_spark_4c_16dp.png",
   102|  "java/res/drawable-mdpi/incognito_splash.png",
   103|  "java/res/drawable-mdpi/infobar_chrome.png",
   104|  "java/res/drawable-mdpi/infobar_translate.png",
   105|  "java/res/drawable-mdpi/location_bar_incognito_badge.png",
   106|  "java/res/drawable-mdpi/menu_update.png",
   107|  "java/res/drawable-mdpi/offline_pin.png",
   108|  "java/res/drawable-mdpi/open_in_new_tab.png",
   109|  "java/res/drawable-mdpi/permission_push_notification_off.png",
   110|  "java/res/drawable-mdpi/preview_pin_round.png",
   111|  "java/res/drawable-mdpi/progress_bar_background.9.png",
   112|  "java/res/drawable-mdpi/progress_bar_foreground.9.png",
   113|  "java/res/drawable-mdpi/reader_mode_prefs_icon.png",
   114|  "java/res/drawable-mdpi/safetytip_shield.png",
   115|  "java/res/drawable-mdpi/shortcut_incognito.png",
   116|  "java/res/drawable-mdpi/shortcut_newtab.png",
   117|  "java/res/drawable-mdpi/shortcut_newwindow.png",
   118|  "java/res/drawable-mdpi/spinner.png",
   119|  "java/res/drawable-mdpi/spinner_white.png",
   120|  "java/res/drawable-mdpi/tab_group_outline.9.png",
   121|  "java/res/drawable-mdpi/tab_indicator_spinner.png",
   122|  "java/res/drawable-night/virtual_card_enrollment_illustration.xml",
   123|  "java/res/drawable-nodpi/bookmark_widget_preview.png",
   124|  "java/res/drawable-nodpi/widget_preview.png",
   125|  "java/res/drawable-xhdpi/btn_close_white.png",
   126|  "java/res/drawable-xhdpi/btn_tab_close_normal.png",
   127|  "java/res/drawable-xhdpi/cvc_icon.png",
   128|  "java/res/drawable-xhdpi/cvc_icon_amex.png",
   129|  "java/res/drawable-xhdpi/ic_devices_16dp.png",
   130|  "java/res/drawable-xhdpi/ic_dialer_icon_blue_40dp.png",
   131|  "java/res/drawable-xhdpi/ic_dialer_not_found_red_40dp.png",
   132|  "java/res/drawable-xhdpi/ic_download_pause.png",
   133|  "java/res/drawable-xhdpi/ic_download_pending.png",
   134|  "java/res/drawable-xhdpi/ic_email_googblue_36dp.png",
   135|  "java/res/drawable-xhdpi/ic_error_grey800_24dp_filled.png",
   136|  "java/res/drawable-xhdpi/ic_error_outline_red_24dp.png",
   137|  "java/res/drawable-xhdpi/ic_error_white_24dp_filled.png",
   138|  "java/res/drawable-xhdpi/ic_event_googblue_36dp.png",
   139|  "java/res/drawable-xhdpi/ic_exit_to_app_white_24dp.png",
   140|  "java/res/drawable-xhdpi/ic_file_download_white_24dp.png",
   141|  "java/res/drawable-xhdpi/ic_link_grey600_36dp.png",
   142|  "java/res/drawable-xhdpi/ic_phone_googblue_36dp.png",
   143|  "java/res/drawable-xhdpi/ic_photo_camera.png",
   144|  "java/res/drawable-xhdpi/ic_place_googblue_36dp.png",
   145|  "java/res/drawable-xhdpi/ic_spark_4c_16dp.png",
   146|  "java/res/drawable-xhdpi/incognito_splash.png",
   147|  "java/res/drawable-xhdpi/infobar_chrome.png",
   148|  "java/res/drawable-xhdpi/infobar_translate.png",
   149|  "java/res/drawable-xhdpi/location_bar_incognito_badge.png",
   150|  "java/res/drawable-xhdpi/menu_update.png",
   151|  "java/res/drawable-xhdpi/offline_pin.png",
   152|  "java/res/drawable-xhdpi/open_in_new_tab.png",
   153|  "java/res/drawable-xhdpi/permission_push_notification_off.png",
   154|  "java/res/drawable-xhdpi/preview_pin_round.png",
   155|  "java/res/drawable-xhdpi/progress_bar_background.9.png",
   156|  "java/res/drawable-xhdpi/progress_bar_foreground.9.png",
   157|  "java/res/drawable-xhdpi/reader_mode_prefs_icon.png",
   158|  "java/res/drawable-xhdpi/safetytip_shield.png",
   159|  "java/res/drawable-xhdpi/shortcut_incognito.png",
   160|  "java/res/drawable-xhdpi/shortcut_newtab.png",
   161|  "java/res/drawable-xhdpi/shortcut_newwindow.png",
   162|  "java/res/drawable-xhdpi/spinner.png",
   163|  "java/res/drawable-xhdpi/spinner_white.png",
   164|  "java/res/drawable-xhdpi/tab_group_outline.9.png",
   165|  "java/res/drawable-xhdpi/tab_indicator_spinner.png",
   166|  "java/res/drawable-xxhdpi/btn_close_white.png",
   167|  "java/res/drawable-xxhdpi/btn_tab_close_normal.png",
   168|  "java/res/drawable-xxhdpi/cvc_icon.png",
   169|  "java/res/drawable-xxhdpi/cvc_icon_amex.png",
   170|  "java/res/drawable-xxhdpi/ic_devices_16dp.png",
   171|  "java/res/drawable-xxhdpi/ic_dialer_icon_blue_40dp.png",
   172|  "java/res/drawable-xxhdpi/ic_dialer_not_found_red_40dp.png",
   173|  "java/res/drawable-xxhdpi/ic_download_pause.png",
   174|  "java/res/drawable-xxhdpi/ic_download_pending.png",
   175|  "java/res/drawable-xxhdpi/ic_email_googblue_36dp.png",
   176|  "java/res/drawable-xxhdpi/ic_error_grey800_24dp_filled.png",
   177|  "java/res/drawable-xxhdpi/ic_error_outline_red_24dp.png",
   178|  "java/res/drawable-xxhdpi/ic_error_white_24dp_filled.png",
   179|  "java/res/drawable-xxhdpi/ic_event_googblue_36dp.png",
   180|  "java/res/drawable-xxhdpi/ic_exit_to_app_white_24dp.png",
   181|  "java/res/drawable-xxhdpi/ic_file_download_white_24dp.png",
   182|  "java/res/drawable-xxhdpi/ic_link_grey600_36dp.png",
   183|  "java/res/drawable-xxhdpi/ic_phone_googblue_36dp.png",
   184|  "java/res/drawable-xxhdpi/ic_photo_camera.png",
   185|  "java/res/drawable-xxhdpi/ic_place_googblue_36dp.png",
   186|  "java/res/drawable-xxhdpi/ic_spark_4c_16dp.png",
   187|  "java/res/drawable-xxhdpi/incognito_splash.png",
   188|  "java/res/drawable-xxhdpi/infobar_chrome.png",
   189|  "java/res/drawable-xxhdpi/infobar_translate.png",
   190|  "java/res/drawable-xxhdpi/location_bar_incognito_badge.png",
   191|  "java/res/drawable-xxhdpi/menu_update.png",
   192|  "java/res/drawable-xxhdpi/offline_pin.png",
   193|  "java/res/drawable-xxhdpi/open_in_new_tab.png",
   194|  "java/res/drawable-xxhdpi/permission_push_notification_off.png",
   195|  "java/res/drawable-xxhdpi/preview_pin_round.png",
   196|  "java/res/drawable-xxhdpi/progress_bar_background.9.png",
   197|  "java/res/drawable-xxhdpi/progress_bar_foreground.9.png",
   198|  "java/res/drawable-xxhdpi/reader_mode_prefs_icon.png",
   199|  "java/res/drawable-xxhdpi/safetytip_shield.png",
   200|  "java/res/drawable-xxhdpi/shortcut_incognito.png",
   201|  "java/res/drawable-xxhdpi/shortcut_newtab.png",
   202|  "java/res/drawable-xxhdpi/shortcut_newwindow.png",
   203|  "java/res/drawable-xxhdpi/spinner.png",
   204|  "java/res/drawable-xxhdpi/spinner_white.png",
   205|  "java/res/drawable-xxhdpi/tab_group_outline.9.png",
   206|  "java/res/drawable-xxhdpi/tab_indicator_spinner.png",
   207|  "java/res/drawable-xxxhdpi/btn_close_white.png",
   208|  "java/res/drawable-xxxhdpi/btn_tab_close_normal.png",
   209|  "java/res/drawable-xxxhdpi/cvc_icon.png",
   210|  "java/res/drawable-xxxhdpi/cvc_icon_amex.png",
   211|  "java/res/drawable-xxxhdpi/ic_devices_16dp.png",
   212|  "java/res/drawable-xxxhdpi/ic_dialer_icon_blue_40dp.png",
   213|  "java/res/drawable-xxxhdpi/ic_dialer_not_found_red_40dp.png",
   214|  "java/res/drawable-xxxhdpi/ic_email_googblue_36dp.png",
   215|  "java/res/drawable-xxxhdpi/ic_error_grey800_24dp_filled.png",
   216|  "java/res/drawable-xxxhdpi/ic_error_outline_red_24dp.png",
   217|  "java/res/drawable-xxxhdpi/ic_error_white_24dp_filled.png",
   218|  "java/res/drawable-xxxhdpi/ic_event_googblue_36dp.png",
   219|  "java/res/drawable-xxxhdpi/ic_exit_to_app_white_24dp.png",
   220|  "java/res/drawable-xxxhdpi/ic_file_download_white_24dp.png",
   221|  "java/res/drawable-xxxhdpi/ic_link_grey600_36dp.png",
   222|  "java/res/drawable-xxxhdpi/ic_phone_googblue_36dp.png",
   223|  "java/res/drawable-xxxhdpi/ic_photo_camera.png",
   224|  "java/res/drawable-xxxhdpi/ic_place_googblue_36dp.png",
   225|  "java/res/drawable-xxxhdpi/ic_spark_4c_16dp.png",
   226|  "java/res/drawable-xxxhdpi/incognito_splash.png",
   227|  "java/res/drawable-xxxhdpi/infobar_chrome.png",
   228|  "java/res/drawable-xxxhdpi/infobar_translate.png",
   229|  "java/res/drawable-xxxhdpi/location_bar_incognito_badge.png",
   230|  "java/res/drawable-xxxhdpi/menu_update.png",
   231|  "java/res/drawable-xxxhdpi/offline_pin.png",
   232|  "java/res/drawable-xxxhdpi/open_in_new_tab.png",
   233|  "java/res/drawable-xxxhdpi/permission_push_notification_off.png",
   234|  "java/res/drawable-xxxhdpi/preview_pin_round.png",
   235|  "java/res/drawable-xxxhdpi/progress_bar_background.9.png",
   236|  "java/res/drawable-xxxhdpi/progress_bar_foreground.9.png",
   237|  "java/res/drawable-xxxhdpi/safetytip_shield.png",
   238|  "java/res/drawable-xxxhdpi/shortcut_incognito.png",
   239|  "java/res/drawable-xxxhdpi/shortcut_newtab.png",
   240|  "java/res/drawable-xxxhdpi/shortcut_newwindow.png",
   241|  "java/res/drawable-xxxhdpi/spinner.png",
   242|  "java/res/drawable-xxxhdpi/spinner_white.png",
   243|  "java/res/drawable-xxxhdpi/tab_group_outline.9.png",
   244|  "java/res/drawable-xxxhdpi/tab_indicator_spinner.png",
   245|  "java/res/drawable/adaptive_toolbar_preference_header.xml",
   246|  "java/res/drawable/add_link.xml",
   247|  "java/res/drawable/arrow_back_24px.xml",
   248|  "java/res/drawable/arrow_down.xml",
   249|  "java/res/drawable/arrow_forward_24px.xml",
   250|  "java/res/drawable/arrow_up.xml",
   251|  "java/res/drawable/auto_pip_permission_dialog_background.xml",
   252|  "java/res/drawable/autofill_save_card_credit_card_surface.xml",
   253|  "java/res/drawable/autorenew_24dp.xml",
   254|  "java/res/drawable/bg_circle_tab_strip_button.xml",
   255|  "java/res/drawable/bg_tabstrip_tab_divider.xml",
   256|  "java/res/drawable/blue_google_shield.xml",
   257|  "java/res/drawable/bolt_24dp.xml",
   258|  "java/res/drawable/bookmark_empty_state_illustration.xml",
   259|  "java/res/drawable/bookmark_title_bar_shadow.xml",
   260|  "java/res/drawable/bookmark_touch_ripple.xml",
   261|  "java/res/drawable/bookmark_widget_background.xml",
   262|  "java/res/drawable/bookmark_widget_layout_preview.xml",
   263|  "java/res/drawable/bookmark_widget_list_selector.xml",
   264|  "java/res/drawable/btn_reload_stop.xml",
   265|  "java/res/drawable/button_borderless_compat.xml",
   266|  "java/res/drawable/button_compat_shape.xml",
   267|  "java/res/drawable/capture_24dp.xml",
   268|  "java/res/drawable/capture_overlay_border.xml",
   269|  "java/res/drawable/card_container_background.xml",
   270|  "java/res/drawable/checkerboard_background.xml",
   271|  "java/res/drawable/checklist.xml",
   272|  "java/res/drawable/checkmark_selection_drawable.xml",
   273|  "java/res/drawable/chrome_logo_on_circular_background.xml",
   274|  "java/res/drawable/clear_text.xml",
   275|  "java/res/drawable/computer_black_24dp.xml",
   276|  "java/res/drawable/custom_tabs_handle_view_shape.xml",
   277|  "java/res/drawable/custom_tabs_url_bar_omnibox_bg.xml",
   278|  "java/res/drawable/default_browser_promo_fre_logo_illustration.xml",
   279|  "java/res/drawable/devices_black_24dp.xml",
   280|  "java/res/drawable/distilled_page_prefs_button_bg.xml",
   281|  "java/res/drawable/down_arrow_on_circular_background.xml",
   282|  "java/res/drawable/draft_spark_24dp.xml",
   283|  "java/res/drawable/focusable_item_foreground.xml",
   284|  "java/res/drawable/fre_promo_chrome_illustration.xml",
   285|  "java/res/drawable/fre_promo_shield_illustration.xml",
   286|  "java/res/drawable/fre_promo_sync_illustration.xml",
   287|  "java/res/drawable/gesture_user_education_iph_bubble_background.xml",
   288|  "java/res/drawable/gesture_user_education_iph_triangle_background.xml",
   289|  "java/res/drawable/google_pay_with_divider.xml",
   290|  "java/res/drawable/gray_shield.xml",
   291|  "java/res/drawable/history_app_empty_state_illustration.xml",
   292|  "java/res/drawable/history_empty_state_illustration.xml",
   293|  "java/res/drawable/ic_account_balance.xml",
   294|  "java/res/drawable/ic_add_box_rounded_corner.xml",
   295|  "java/res/drawable/ic_add_round_20dp.xml",
   296|  "java/res/drawable/ic_add_to_home_screen.xml",
   297|  "java/res/drawable/ic_arrow_forward_blue_24dp.xml",
   298|  "java/res/drawable/ic_auto_awesome.xml",
   299|  "java/res/drawable/ic_block_red.xml",
   300|  "java/res/drawable/ic_checkmark_24dp.xml",
   301|  "java/res/drawable/ic_cloud_off_24dp.xml",
   302|  "java/res/drawable/ic_cloud_offline_24dp.xml",
   303|  "java/res/drawable/ic_colorize_24dp.xml",
   306|  "java/res/drawable/ic_dev_tools_24dp.xml",
   307|  "java/res/drawable/ic_drag_handle_24dp.xml",
   308|  "java/res/drawable/ic_error.xml",
   309|  "java/res/drawable/ic_features_24dp.xml",
   310|  "java/res/drawable/ic_feedback_24dp.xml",
   311|  "java/res/drawable/ic_file_save_24dp.xml",
   312|  "java/res/drawable/ic_find_in_page.xml",
   313|  "java/res/drawable/ic_folder_outline_24dp.xml",
   314|  "java/res/drawable/ic_forward_arrow_black_24dp.xml",
   315|  "java/res/drawable/ic_fullscreen_enter.xml",
   316|  "java/res/drawable/ic_fullscreen_exit.xml",
   317|  "java/res/drawable/ic_google_services_24dp.xml",
   318|  "java/res/drawable/ic_google_services_48dp.xml",
   319|  "java/res/drawable/ic_google_services_48dp_containment.xml",
   320|  "java/res/drawable/ic_google_services_48dp_with_bg.xml",
   321|  "java/res/drawable/ic_google_services_48dp_with_bg_containment.xml",
   322|  "java/res/drawable/ic_group_24dp.xml",
   323|  "java/res/drawable/ic_image_descriptions.xml",
   324|  "java/res/drawable/ic_incognito_reauth_promo_icon.xml",
   328|  "java/res/drawable/ic_minimize.xml",
   329|  "java/res/drawable/ic_mobile_friendly_24dp.xml",
   330|  "java/res/drawable/ic_more_tools_24dp.xml",
   331|  "java/res/drawable/ic_new_window.xml",
   332|  "java/res/drawable/ic_open_in_browser.xml",
   333|  "java/res/drawable/ic_open_webapk.xml",
   335|  "java/res/drawable/ic_password_manager_key_off.xml",
   336|  "java/res/drawable/ic_person_add.xml",
   337|  "java/res/drawable/ic_person_add_40dp.xml",
   338|  "java/res/drawable/ic_picture_in_picture_alt_24dp.xml",
   339|  "java/res/drawable/ic_play_circle.xml",
   340|  "java/res/drawable/ic_reading_list_folder_24dp.xml",
   341|  "java/res/drawable/ic_recent_tabs_bulk_20dp.xml",
   342|  "java/res/drawable/ic_refresh_24dp_rtl.xml",
   343|  "java/res/drawable/ic_select_check_box_24dp.xml",
   344|  "java/res/drawable/ic_select_window.xml",
   345|  "java/res/drawable/ic_shoppingmode_24dp.xml",
   346|  "java/res/drawable/ic_signout_40dp.xml",
   347|  "java/res/drawable/ic_site_timer.xml",
   348|  "java/res/drawable/ic_spark_24dp.xml",
   349|  "java/res/drawable/ic_spark_blue_16dp.xml",
   353|  "java/res/drawable/ic_storefront_blue.xml",
   354|  "java/res/drawable/ic_sync_error_legacy_24dp.xml",
   355|  "java/res/drawable/ic_tab_close_24dp.xml",
   356|  "java/res/drawable/ic_tab_icon_24dp.xml",
   357|  "java/res/drawable/ic_task_manager_24dp.xml",
   358|  "java/res/drawable/ic_toolbar_24dp.xml",
   359|  "java/res/drawable/ic_toolbar_share_offset_24dp.xml",
   360|  "java/res/drawable/ic_translate.xml",
   361|  "java/res/drawable/ic_trending_down_24dp.xml",
   362|  "java/res/drawable/ic_update_24dp.xml",
   363|  "java/res/drawable/ic_warning_white_24dp.xml",
   364|  "java/res/drawable/ic_webstore_menu.xml",
   366|  "java/res/drawable/improved_bookmark_row_visual_background.xml",
   367|  "java/res/drawable/improved_bookmark_save_flow_multi_pane_bottom_background.xml",
   368|  "java/res/drawable/improved_bookmark_save_flow_multi_pane_top_background.xml",
   369|  "java/res/drawable/improved_bookmark_save_flow_single_pane_background.xml",
   370|  "java/res/drawable/incognito_history_placeholder_image.xml",
   371|  "java/res/drawable/incognito_indicator_background.xml",
   372|  "java/res/drawable/infobar_autofill_cc.xml",
   373|  "java/res/drawable/lens_camera_icon.xml",
   374|  "java/res/drawable/long_screenshot.xml",
   375|  "java/res/drawable/material_ic_check_24dp.xml",
   376|  "java/res/drawable/material_ic_check_circle_filled_24dp.xml",
   377|  "java/res/drawable/material_ic_create_new_folder_24dp.xml",
   378|  "java/res/drawable/material_ic_drive_file_move_24dp.xml",
   379|  "java/res/drawable/material_tooltip_background.xml",
   380|  "java/res/drawable/menu_button_background.xml",
   381|  "java/res/drawable/menu_button_background_selector.xml",
   382|  "java/res/drawable/menu_dot.xml",
   383|  "java/res/drawable/new_tab_animation_rounded_rect.xml",
   384|  "java/res/drawable/notifications_active.xml",
   385|  "java/res/drawable/permission_location_off.xml",
   386|  "java/res/drawable/phone_recent_tab_empty_state_illustration.xml",
   389|  "java/res/drawable/pill_background.xml",
   390|  "java/res/drawable/price_tracking_disabled.xml",
   391|  "java/res/drawable/price_tracking_enabled_filled.xml",
   392|  "java/res/drawable/price_tracking_enabled_outline.xml",
   393|  "java/res/drawable/qr_code.xml",
   394|  "java/res/drawable/radio_button_checked_24dp.xml",
   395|  "java/res/drawable/reading_list_empty_state_illustration.xml",
   396|  "java/res/drawable/receipt_long.xml",
   397|  "java/res/drawable/search_activity_bg.xml",
   398|  "java/res/drawable/send_tab.xml",
   399|  "java/res/drawable/settings_no_match.xml",
   400|  "java/res/drawable/settings_zero_state.xml",
   401|  "java/res/drawable/shared_clipboard_zero_state_dark.xml",
   402|  "java/res/drawable/shared_clipboard_zero_state_light.xml",
   403|  "java/res/drawable/sharing_more.xml",
   404|  "java/res/drawable/sharing_print.xml",
   405|  "java/res/drawable/shopping_accessory_view_background.xml",
   406|  "java/res/drawable/steps_number_circle_background.xml",
   407|  "java/res/drawable/tab_close_button_bg.xml",
   408|  "java/res/drawable/tab_indicator.xml",
   409|  "java/res/drawable/tablet_black_24dp.xml",
   410|  "java/res/drawable/tablet_recent_tab_empty_state_illustration.xml",
   412|  "java/res/drawable/text_cursor_lowend.xml",
   413|  "java/res/drawable/tips_opt_in_logo.xml",
   414|  "java/res/drawable/tips_promo_bottom_omnibox_logo.xml",
   415|  "java/res/drawable/tips_promo_create_tab_groups_logo.xml",
   416|  "java/res/drawable/tips_promo_customize_mvt_logo.xml",
   417|  "java/res/drawable/tips_promo_esb_logo.xml",
   418|  "java/res/drawable/tips_promo_lens_logo.xml",
   419|  "java/res/drawable/tips_promo_password_autofill_logo.xml",
   420|  "java/res/drawable/tips_promo_recent_tabs_logo.xml",
   421|  "java/res/drawable/tips_promo_signin_logo.xml",
   422|  "java/res/drawable/travel_explore_24dp.xml",
   423|  "java/res/drawable/unfold_less.xml",
   424|  "java/res/drawable/unfold_more.xml",
   425|  "java/res/drawable/view_list_bottom_item_background.xml",
   426|  "java/res/drawable/view_list_normal_item_background.xml",
   427|  "java/res/drawable/view_list_single_item_background.xml",
   428|  "java/res/drawable/view_list_top_item_background.xml",
   429|  "java/res/drawable/virtual_card_enrollment_illustration.xml",
   430|  "java/res/drawable/volume_off_24dp.xml",
   431|  "java/res/drawable/volume_up_24dp.xml",
   432|  "java/res/drawable/window_controls_overlay_toggle.xml",
   433|  "java/res/drawable/xr_toolbar_rounded_rect.xml",
   434|  "java/res/font/reader_mode_lexend.xml",
   435|  "java/res/font/geist.ttf",
   436|  "java/res/font/geist_italic.ttf",
   437|  "java/res/font/geist_mono.ttf",
   438|  "java/res/font/geist_mono_italic.ttf",
   439|  "java/res/font/geist_family.xml",
   440|  "java/res/layout-sw600dp/find_toolbar.xml",
   441|  "java/res/layout/account_chooser_dialog_item.xml",
   442|  "java/res/layout/account_chooser_dialog_title.xml",
   443|  "java/res/layout/account_management_account_row.xml",
   444|  "java/res/layout/app_history_filter.xml",
   445|  "java/res/layout/auto_pip_permission_dialog.xml",
   446|  "java/res/layout/auto_sign_in_first_run_dialog.xml",
   447|  "java/res/layout/autofill_billing_address_dropdown.xml",
   448|  "java/res/layout/autofill_card_name_and_number.xml",
   449|  "java/res/layout/autofill_card_unmask_prompt.xml",
   450|  "java/res/layout/autofill_cc_details.xml",
   451|  "java/res/layout/autofill_cc_details_new.xml",
   452|  "java/res/layout/autofill_expiration_date_fix_flow.xml",
   453|  "java/res/layout/autofill_name_fixflow.xml",
   454|  "java/res/layout/autofill_save_card_base_layout.xml",
   455|  "java/res/layout/autofill_save_card_bottom_sheet.xml",
   456|  "java/res/layout/autofill_save_iban_bottom_sheet.xml",
   457|  "java/res/layout/autofill_server_card_editor.xml",
   458|  "java/res/layout/autofill_server_data_edit_link.xml",
   459|  "java/res/layout/autofill_server_data_label.xml",
   460|  "java/res/layout/autofill_settings_home_profile_icon.xml",
   461|  "java/res/layout/autofill_settings_local_profile_icon.xml",
   462|  "java/res/layout/autofill_settings_work_profile_icon.xml",
   463|  "java/res/layout/bookmark_activity.xml",
   464|  "java/res/layout/bookmark_add_new_folder_input_layout.xml",
   465|  "java/res/layout/bookmark_bar.xml",
   466|  "java/res/layout/bookmark_bar_button.xml",
   467|  "java/res/layout/bookmark_bar_overflow_button_wrapper.xml",
   468|  "java/res/layout/bookmark_edit.xml",
   469|  "java/res/layout/bookmark_folder_picker.xml",
   470|  "java/res/layout/bookmark_main.xml",
   471|  "java/res/layout/bookmark_search_box_row.xml",
   472|  "java/res/layout/bookmark_section_header.xml",
   473|  "java/res/layout/bookmark_section_header_v2.xml",
   474|  "java/res/layout/bookmark_toolbar.xml",
   475|  "java/res/layout/bookmark_widget.xml",
   476|  "java/res/layout/bookmark_widget_icons_only.xml",
   477|  "java/res/layout/bookmark_widget_item.xml",
   478|  "java/res/layout/bookmark_widget_preview_layout.xml",
   479|  "java/res/layout/bookmark_widget_section_header.xml",
   480|  "java/res/layout/bottom_sheet_container.xml",
   481|  "java/res/layout/caret_browsing_ask_again_view.xml",
   482|  "java/res/layout/chrome_item_picker_activity.xml",
   483|  "java/res/layout/clear_browsing_data_button.xml",
   484|  "java/res/layout/clear_browsing_important_dialog_listview.xml",
   485|  "java/res/layout/compositor_view_holder.xml",
   486|  "java/res/layout/confirm_important_sites_list_row.xml",
   487|  "java/res/layout/context_menu.xml",
   488|  "java/res/layout/context_menu_chip.xml",
   489|  "java/res/layout/context_menu_fullscreen_container.xml",
   490|  "java/res/layout/context_menu_header.xml",
   491|  "java/res/layout/context_menu_header_text.xml",
   492|  "java/res/layout/context_menu_row.xml",
   493|  "java/res/layout/contextual_search_callout_view.xml",
   494|  "java/res/layout/contextual_search_caption_view.xml",
   495|  "java/res/layout/contextual_search_card_icon_view.xml",
   496|  "java/res/layout/contextual_search_context_view.xml",
   497|  "java/res/layout/contextual_search_promo_view.xml",
   498|  "java/res/layout/contextual_search_quick_action_icon_view.xml",
   499|  "java/res/layout/contextual_search_related_searches_view.xml",
   500|  "java/res/layout/contextual_search_term_view.xml",
   501|  "java/res/layout/custom_tab_close_button.xml",
   502|  "java/res/layout/custom_tab_desktop_popup_header_layout.xml",
   503|  "java/res/layout/custom_tab_desktop_popup_main_layout.xml",
   504|  "java/res/layout/custom_tab_incognito_icon.xml",
   505|  "java/res/layout/custom_tab_menu_button.xml",
   506|  "java/res/layout/custom_tabs_bottombar.xml",
   507|  "java/res/layout/custom_tabs_bottombar_item.xml",
   508|  "java/res/layout/custom_tabs_control_container.xml",
   509|  "java/res/layout/custom_tabs_handle_view.xml",
   510|  "java/res/layout/custom_tabs_minimize_button.xml",
   511|  "java/res/layout/custom_tabs_minimized_card.xml",
   512|  "java/res/layout/custom_tabs_sidepanel_maximize.xml",
   513|  "java/res/layout/custom_tabs_toolbar_button.xml",
   514|  "java/res/layout/custom_tabs_topbar.xml",
   515|  "java/res/layout/custom_tile_edit_layout.xml",
   516|  "java/res/layout/custom_view_menu_item.xml",
   517|  "java/res/layout/date_view.xml",
   518|  "java/res/layout/default_browser_promo_fre_landscape_view.xml",
   519|  "java/res/layout/default_browser_promo_fre_portrait_view.xml",
   520|  "java/res/layout/default_browser_promo_fre_row.xml",
   521|  "java/res/layout/default_search_engine_first_run_fragment.xml",
   522|  "java/res/layout/distilled_page_font_family_spinner.xml",
   523|  "java/res/layout/distilled_page_prefs_view.xml",
   524|  "java/res/layout/document_picture_in_picture_header_layout.xml",
   525|  "java/res/layout/document_picture_in_picture_main_layout.xml",
   526|  "java/res/layout/empty_accessory_sheet.xml",
   527|  "java/res/layout/fake_search_box_layout.xml",
   528|  "java/res/layout/find_in_page.xml",
   529|  "java/res/layout/find_toolbar.xml",
   530|  "java/res/layout/finds_opt_in_bottom_sheet.xml",
   531|  "java/res/layout/finds_opt_in_bottom_sheet_content.xml",
   532|  "java/res/layout/fre_tos_privacy_disclaimer.xml",
   533|  "java/res/layout/gesture_user_education_iph_layout.xml",
   534|  "java/res/layout/google_wallet_widget.xml",
   535|  "java/res/layout/hats_survey_container.xml",
   536|  "java/res/layout/history_clear_browsing_data_header.xml",
   537|  "java/res/layout/history_item_view.xml",
   538|  "java/res/layout/history_main.xml",
   539|  "java/res/layout/history_privacy_disclaimer_header.xml",
   540|  "java/res/layout/history_toolbar.xml",
   541|  "java/res/layout/icon_after_title_view.xml",
   542|  "java/res/layout/improved_bookmark_folder_view_layout.xml",
   543|  "java/res/layout/improved_bookmark_row_content.xml",
   544|  "java/res/layout/improved_bookmark_row_layout.xml",
   545|  "java/res/layout/improved_bookmark_row_layout_visual.xml",
   546|  "java/res/layout/improved_bookmark_save_flow.xml",
   547|  "java/res/layout/incognito_description_layout.xml",
   548|  "java/res/layout/incognito_history_placeholder.xml",
   549|  "java/res/layout/incognito_indicator.xml",
   550|  "java/res/layout/incognito_tracking_protection_card.xml",
   551|  "java/res/layout/infobar_footer.xml",
   552|  "java/res/layout/legacy_sync_promo_view.xml",
   553|  "java/res/layout/lightweight_fre_tos.xml",
   554|  "java/res/layout/list_menu_button.xml",
   555|  "java/res/layout/long_screenshots_area_selection_dialog.xml",
   556|  "java/res/layout/manage_space_activity.xml",
   557|  "java/res/layout/material_tooltip.xml",
   558|  "java/res/layout/multiline_spinner_item.xml",
   559|  "java/res/layout/mv_tiles_layout.xml",
   560|  "java/res/layout/navigation_bubble.xml",
   561|  "java/res/layout/navigation_sheet.xml",
   562|  "java/res/layout/navigation_sheet_toolbar.xml",
   563|  "java/res/layout/new_background_tab_animation_host_view.xml",
   564|  "java/res/layout/new_background_tab_animation_tab_switcher_icon.xml",
   565|  "java/res/layout/new_custom_tab_toolbar.xml",
   566|  "java/res/layout/new_tab_page_incognito.xml",
   567|  "java/res/layout/new_tab_page_layout.xml",
   568|  "java/res/layout/open_full_chrome_history_header.xml",
   569|  "java/res/layout/optional_toolbar_button.xml",
   570|  "java/res/layout/os_version_unsupported_text.xml",
   571|  "java/res/layout/other_forms_of_history_dialog.xml",
   572|  "java/res/layout/page_zoom_menu_item.xml",
   573|  "java/res/layout/password_manager_dialog.xml",
   574|  "java/res/layout/password_manager_dialog_with_help_button.xml",
   576|  "java/res/layout/powered_by_chrome_footer.xml",
   577|  "java/res/layout/radio_button_group_homepage_preference.xml",
   578|  "java/res/layout/reader_mode_bottom_sheet.xml",
   579|  "java/res/layout/reader_mode_prefs_bottom_content.xml",
   580|  "java/res/layout/reader_mode_prefs_bottom_content_with_toggle_links.xml",
   581|  "java/res/layout/reader_mode_prefs_view.xml",
   582|  "java/res/layout/recent_tabs_group_item.xml",
   583|  "java/res/layout/recent_tabs_group_separator_invisible.xml",
   584|  "java/res/layout/recent_tabs_group_separator_visible.xml",
   585|  "java/res/layout/recent_tabs_list_item.xml",
   586|  "java/res/layout/recent_tabs_page.xml",
   587|  "java/res/layout/search_activity.xml",
   588|  "java/res/layout/search_widget_template.xml",
   589|  "java/res/layout/send_tab_to_self_device_picker_footer.xml",
   590|  "java/res/layout/send_tab_to_self_device_picker_item.xml",
   591|  "java/res/layout/send_tab_to_self_device_picker_list.xml",
   592|  "java/res/layout/send_tab_to_self_device_picker_toolbar.xml",
   593|  "java/res/layout/send_tab_to_self_feature_unavailable_prompt.xml",
   594|  "java/res/layout/send_tab_to_self_manage_devices_link.xml",
   595|  "java/res/layout/settings_activity.xml",
   596|  "java/res/layout/settings_preference_detail_pane.xml",
   597|  "java/res/layout/settings_recent_searches_preference_category.xml",
   598|  "java/res/layout/settings_search_box.xml",
   599|  "java/res/layout/settings_search_query.xml",
   600|  "java/res/layout/share_sheet_content.xml",
   601|  "java/res/layout/share_sheet_item.xml",
   602|  "java/res/layout/shopping_accessory_view_layout.xml",
   603|  "java/res/layout/status_indicator_container.xml",
   604|  "java/res/layout/suggestions_tile_view_condensed.xml",
   605|  "java/res/layout/suspended_tab.xml",
   606|  "java/res/layout/sync_custom_passphrase.xml",
   607|  "java/res/layout/sync_enter_passphrase.xml",
   608|  "java/res/layout/sync_passphrase_types.xml",
   609|  "java/res/layout/tab_strip_group_menu_layout.xml",
   610|  "java/res/layout/tab_switcher_action_menu_layout.xml",
   611|  "java/res/layout/tab_switcher_module_container.xml",
   612|  "java/res/layout/tab_switcher_view_holder.xml",
   613|  "java/res/layout/tips_opt_in_bottom_sheet.xml",
   614|  "java/res/layout/tips_promo_bottom_sheet.xml",
   615|  "java/res/layout/tips_promo_detail_sheet.xml",
   616|  "java/res/layout/tips_promo_main_sheet.xml",
   617|  "java/res/layout/tips_promo_step_item.xml",
   618|  "java/res/layout/update_menu_item.xml",
   619|  "java/res/layout/url_bar.xml",
   620|  "java/res/layout/virtual_card_enrollment_dialog.xml",
   621|  "java/res/layout/webapk_icon_name_update_dialog.xml",
   622|  "java/res/layout/webapk_update_report_abuse_custom_view.xml",
   623|  "java/res/menu/app_specific_history_manager_menu.xml",
   624|  "java/res/menu/bookmark_folder_picker_menu.xml",
   625|  "java/res/menu/bookmark_toolbar_menu_improved.xml",
   626|  "java/res/menu/history_manager_menu.xml",
   627|  "java/res/raw/back_gesture_arrow_animation.json",
   628|  "java/res/raw/finds_opt_in_animation.json",
   629|  "java/res/raw/tips_notifications_quick_delete_logo_anim.json",
   630|  "java/res/transition/fade.xml",
   631|  "java/res/transition/move_image.xml",
   632|  "java/res/values-h600dp/dimens.xml",
   633|  "java/res/values-hdpi/dimens.xml",
   634|  "java/res/values-land/styles.xml",
   635|  "java/res/values-large/drawables.xml",
   636|  "java/res/values-ldrtl/drawables.xml",
   637|  "java/res/values-night/colors.xml",
   638|  "java/res/values-night/drawables.xml",
   639|  "java/res/values-sw600dp-v30/styles.xml",
   640|  "java/res/values-sw600dp/dimens.xml",
   641|  "java/res/values-sw600dp/styles.xml",
   642|  "java/res/values-sw600dp/values.xml",
   643|  "java/res/values-v31/styles.xml",
   644|  "java/res/values-w412dp/bools.xml",
   645|  "java/res/values-w600dp/dimens.xml",
   646|  "java/res/values/attrs.xml",
   647|  "java/res/values/bools.xml",
   648|  "java/res/values/colors.xml",
   649|  "java/res/values/dimens.xml",
   650|  "java/res/values/drawables.xml",
   651|  "java/res/values/ids.xml",
   652|  "java/res/values/strings.xml",
   653|  "java/res/values/styles.xml",
   654|  "java/res/values/values.xml",
   655|  "java/res/xml/about_chrome_preferences.xml",
   656|  "java/res/xml/account_management_preferences.xml",
   657|  "java/res/xml/ad_services_config.xml",
   658|  "java/res/xml/appearance_preferences.xml",
   659|  "java/res/xml/bookmark_widget_info.xml",
   660|  "java/res/xml/clear_browsing_data_preferences.xml",
   661|  "java/res/xml/contextual_search_preferences.xml",
   662|  "java/res/xml/developer_preferences.xml",
   663|  "java/res/xml/do_not_track_preferences.xml",
   664|  "java/res/xml/google_services_preferences.xml",
   665|  "java/res/xml/homepage_preferences.xml",
   666|  "java/res/xml/legal_information_preferences.xml",
   667|  "java/res/xml/main_preferences.xml",
   668|  "java/res/xml/personalize_google_services_preferences.xml",
   669|  "java/res/xml/privacy_preferences.xml",
   670|  "java/res/xml/search_widget_info.xml",
   671|  "java/res/xml/tracing_preferences.xml",
   672|  "java/res/xml/unified_account_settings_preferences.xml",
   673|]
   674|